### ISSUE TITLE
Apparizione di Titolo e Sala al passaggio del mouse

### ISSUE THREAD

**Issue by fschtn** [francescosche/Progetto-LTW-2017-18#4]
Sulla home page (nel file "index.html"), si potrebbe pensare di far apparire il titolo del file e il numero della sala in cui esso viene proiettato al passaggio del mouse.
Ad esempio, scurendo la locandina del file e facendo apparire il titolo e il numero di sala in sovrimpressione, magari in bianco.

**Comment by fschtn** [comment]
@felixmassotti che ne dici? Fattibile?

**Comment by Felixmassotti** [comment]
Si non sarebbe male come idea 👍
